<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>PointsView</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.10" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="VayuRays.Core">
      <HintPath>C:\TT\VayuRays\VayuRays.Core\bin\Debug\net10.0\VayuRays.Core.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>
